# Generated by Django 4.2.3 on 2023-11-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='fulfillment_rate',
            new_name='fulfilment_rate',
        ),
    ]
